pull_request_rules:
  - name: Automatic merge for scala-steward PRs - patch
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - status-success=CI / Microsite (pull_request)
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: squash
  - name: Automatic merge for scala-steward PRs - minor
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - status-success=CI / Microsite (pull_request)
      - body~=labels:.*semver-minor
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
