jobs:
  include:
#    - stage: build
#      sudo: false
#      language: scala
#      jdk:
#        - oraclejdk8
#      scala:
#        - 2.12.8
#      before_cache:
#        - find $HOME/.sbt -name "*.lock" -type f -delete
#        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
#      cache:
#        directories:
#          - "$HOME/.ivy2/cache"
#          - "$HOME/.coursier/cache"
#          - "$HOME/.sbt"
#      before_install:
#        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc
#          -K $encrypted_0b1d2d2bb383_key -iv $encrypted_0b1d2d2bb383_iv -in secring.gpg.enc -out secring.gpg -d; fi
#        - export PATH=${PATH}:./vendor/bundle
#      install:
#        - rvm use 2.3.3 --install --fuzzy
#        - gem update --system
#        - gem install sass
#        - gem install jekyll-watch -v 2.1.2
#        - gem install jekyll -v 3.8.3
#      script:
#        - sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
#      after_success:
#        - sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
    - stage: publish-docker
      sudo: required
      services:
        - docker
#      before_install:
#        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      script:
        - export VERSION=cut -d'=' -f2  version.sbt | sed -e 's/^[ \t]*//;s/"//g'
        - docker build --build-arg PROJECT=server --build-arg VERSION=$VERSION -t compendium/server:latest .
      deploy:
        provider: script
        script:
          docker push compendium/server:latest
        branch: master
