env:
  - DOCKER_USER=47deg

jobs:
  include:
    - stage: build & publish
      name: docker build & publish
      services:
        - docker
      before_cache:
        - >
          mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
          | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
      cache:
        bundler: true
        directories:
          - $HOME/docker
      before_script:
        # Load cached docker images
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
      script:
        - export VERSION=$(cut -d'=' -f2  version.sbt | sed -e 's/^[ \t]*//;s/"//g')
        - docker build --build-arg VERSION=$VERSION -t $DOCKER_USER/compendium:$VERSION -t $DOCKER_USER/compendium:latest .
      deploy:
        provider: script
        script: bash docker_push.sh $DOCKER_PASSWORD $DOCKER_USER
        on:
          branch: master
