---
name: CI

on: [pull_request, push]

env:
  JAVA_VERSION: adopt@v8
  RUBY_VERSION: '2.6'

jobs:

  microsite:
    name: Microsite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache-microsite
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-microsite-${{ hashFiles('**/build.sbt') }}
      - name: Install Jekyll
        run: gem install jekyll -v 4
      - name: Build microsite
        run: sbt docs/makeMicrosite

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-scalafmt-${{ hashFiles('**/project/plugins.sbt') }}
      - name: Check sbt files
        run: sbt scalafmtSbtCheck
      - name: Check scala files
        run: sbt scalafmtCheckAll

  compile:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt compile test:compile
      - name: Test
        run: sbt test
      - uses: actions/upload-artifact@v1
        with:
          name: target
          path: ./target
      - uses: actions/upload-artifact@v1
        with:
          name: project
          path: ./project

  package:
    name: Package
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - uses: actions/download-artifact@v1
        with:
          name: target
      - uses: actions/download-artifact@v1
        with:
          name: project
      - name: Package
        run: sbt universal:packageZipTarball
      - uses: actions/upload-artifact@v1
        with:
          name: package-zip
          path: ./target/universal
